const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('eAPI', {
  winMin: () => ipcRenderer.invoke('win-min'),
  winMax: () => ipcRenderer.invoke('win-max'),
  winClose: () => ipcRenderer.invoke('win-close'),
  winIsMax: () => ipcRenderer.invoke('win-is-max'),
  sessionCreate: (id, config) => ipcRenderer.invoke('session-create', id, config),
  sessionRegister: (id, config) => ipcRenderer.invoke('session-register', id, config),
  sessionClear: (id, ephem) => ipcRenderer.invoke('session-clear', id, ephem),
  sessionBurn: (id, ephem) => ipcRenderer.invoke('session-burn', id, ephem),
  sessionStats: (id, ephem) => ipcRenderer.invoke('session-stats', id, ephem),
  sessionBlockedCount: (id) => ipcRenderer.invoke('session-blocked-count', id),
  sessionTemplates: () => ipcRenderer.invoke('session-templates'),
  fingerprintScript: () => ipcRenderer.invoke('fingerprint-script'),
  sessionApplySettings: () => ipcRenderer.invoke('session-apply-settings'),
  privacyLoad: () => ipcRenderer.invoke('privacy-load'),
  privacySave: (d) => ipcRenderer.invoke('privacy-save', d),
  siteExceptionSet: (host, action) => ipcRenderer.invoke('site-exception-set', host, action),
  syncExport: (pass, data) => ipcRenderer.invoke('sync-export', pass, data),
  syncImport: (pass, vault) => ipcRenderer.invoke('sync-import', pass, vault),
  syncExportFile: (pass) => ipcRenderer.invoke('sync-export-file', pass),
  syncImportFile: (pass) => ipcRenderer.invoke('sync-import-file', pass),
  usersInit: () => ipcRenderer.invoke('users-init'),
  onboardingComplete: (d) => ipcRenderer.invoke('onboarding-complete', d),
  usersSwitch: (id) => ipcRenderer.invoke('users-switch', id),
  usersCreate: (d) => ipcRenderer.invoke('users-create', d),
  usersRemove: (id) => ipcRenderer.invoke('users-remove', id),
  userMainPartition: () => ipcRenderer.invoke('user-main-partition'),
  sessionSave: (d) => ipcRenderer.invoke('session-save', d),
  sessionLoad: () => ipcRenderer.invoke('session-load'),
  validateUrl: (url) => ipcRenderer.invoke('validate-url', url),
  historyLoad: () => ipcRenderer.invoke('history-load'),
  historyAdd: (e) => ipcRenderer.invoke('history-add', e),
  historyClear: () => ipcRenderer.invoke('history-clear'),
  historyDelete: (url) => ipcRenderer.invoke('history-delete', url),
  bmLoad: () => ipcRenderer.invoke('bm-load'),
  bmSave: (d) => ipcRenderer.invoke('bm-save', d),
  exportBookmarks: (d) => ipcRenderer.invoke('export-bookmarks', d),
  importBookmarks: () => ipcRenderer.invoke('import-bookmarks'),
  settingsLoad: () => ipcRenderer.invoke('settings-load'),
  settingsSave: (d) => ipcRenderer.invoke('settings-save', d),
  notesLoad: () => ipcRenderer.invoke('notes-load'),
  notesSave: (t) => ipcRenderer.invoke('notes-save', t),
  clearBrowsingData: () => ipcRenderer.invoke('clear-browsing-data'),
  blockedCount: () => ipcRenderer.invoke('blocked-count'),
  blockedReset: () => ipcRenderer.invoke('blocked-reset'),
  saveScreenshot: (bytes) => ipcRenderer.invoke('save-screenshot', bytes),
  dlList: () => ipcRenderer.invoke('dl-list'),
  dlPause: (id) => ipcRenderer.invoke('dl-pause', id),
  dlResume: (id) => ipcRenderer.invoke('dl-resume', id),
  dlCancel: (id) => ipcRenderer.invoke('dl-cancel', id),
  dlRemove: (id) => ipcRenderer.invoke('dl-remove', id),
  openFile: (p) => ipcRenderer.invoke('open-file', p),
  openExternal: (u) => ipcRenderer.invoke('open-external', u),
  clipboard: (t) => ipcRenderer.invoke('clipboard', t),
  appVersion: () => ipcRenderer.invoke('app-version'),
  appIconUrl: () => ipcRenderer.invoke('app-icon-url'),
  osPrefersDark: () => ipcRenderer.invoke('os-prefers-dark'),
  checkForUpdate: () => ipcRenderer.invoke('check-for-update'),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate: (opts) => ipcRenderer.invoke('install-update', opts),
  quitAndInstall: () => ipcRenderer.invoke('quit-and-install'),
  updateStatus: () => ipcRenderer.invoke('update-status'),
  hasActiveDownloads: () => ipcRenderer.invoke('has-active-downloads'),
  onUpdateProgress: (fn) => ipcRenderer.on('update-progress', (_, d) => fn(d)),
  onUpdateDownloaded: (fn) => ipcRenderer.on('update-downloaded', (_, d) => fn(d)),
  onUpdateError: (fn) => ipcRenderer.on('update-error', (_, d) => fn(d)),
  onUpdateAvailable: (fn) => ipcRenderer.on('update-available', (_, d) => fn(d)),
  chromiumVersion: () => ipcRenderer.invoke('chromium-version'),
  electronVersion: () => ipcRenderer.invoke('electron-version'),
  contextMenu: (p) => ipcRenderer.invoke('context-menu', p),
  openDevTools: () => ipcRenderer.invoke('open-devtools'),
  on: (ch, fn) => ipcRenderer.on(ch, (_, ...a) => fn(...a)),
  off: (ch, fn) => ipcRenderer.off(ch, fn),
});
